global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: "INFO"
  filePath: "/logs/traefik.log"

api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"

  https:
    address: ":443"

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /letsencrypt/acme.json
      email: aaa@bbb.ccc
      httpChallenge:
        entryPoint: "http"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/dynamic"
    watch: true