global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: "INFO"
  filePath: "/logs/traefik.log"

api:
  dashboard: true
  debug: true
  insecure: true

entryPoints:
  http:
    address: ":80" # Create an entrypoint called "http" that uses port 80
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"

  https:
    address: ":443" # Create an entrypoint called "https" that uses port 443

serversTransport:
  insecureSkipVerify: true

certificatesResolvers:
  # Define "letsencrypt" certificate resolver
  letsencrypt:
    acme:
      storage: /letsencrypt/acme.json # Defines the path where certificates should be stored
      email: dhoni@techworks.id # Where LE sends notification about certificates expiring
      httpChallenge:
        entryPoint: "http"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/dynamic_conf" # Adjust the path according your needs.
    watch: true